--DATABASE EXPLORATION --

--Explore all object in Databases 
select * from INFORMATION_SCHEMA.TABLES

--explore all the columns in the data base 
select * from INFORMATION_SCHEMA.COLUMNS 
where TABLE_NAME='dim_customers'


--DIMENSION EXPLORATION--

--Explore all the countries our customer comes from
select distinct(country)from gold.dim_customers

--- explore all the categories or major divisions in the product table 
select distinct(category),subcategory,product_name
from gold.dim_products

--DATE EXPLORATIONS--
--find all first and last date of the dateset

select min(order_date) as first_order_date,max(order_date) as last_order_date,
DATEDIFF(YEAR,MIN(order_date),max(order_date)) year_between  
from gold.fact_sales;
-- find the youngest and oldest customer ?
select max(birthdate),min(birthdate),
DATEDIFF(year,min(birthdate),getdate()) old_age,
DATEDIFF(year,max(birthdate),getdate()) young_age 
from gold.dim_customers


--MEASURE EXPLORATION--
-- Find the  Total Sales?
select sum(sales_amount) as total_amount from gold.fact_sales 

-- Find total quantity of item sold ?
select sum(quantity) as Total_Quantity from gold.fact_sales

-- Avg Selling price ?
select avg(price) as avg_price from gold.fact_sales

--Find the total Number of Orders
select count(order_number) as total_order_count from gold.fact_sales
select count(distinct(order_number)) as total_order_count from gold.fact_sales

--Find the Total Number of Product
select count(product_key) from gold.dim_products
select count(distinct(product_key)) from gold.dim_products

-- find the total number of customer
select count(customer_key)from gold.dim_customers

--Find the Total number of customer that have placed order 
select count(distinct(customer_key)) from gold.fact_sales
 
 -- Generate  Report that Shows all key metrics of the business 

 select 'Total Sales' Measure_Name ,sum(sales_amount) as Measure_Value from gold.fact_sales 
 Union all 
 select 'Total Quantity' Measure_Name ,sum(quantity) as Measure_Value from gold.fact_sales 
 Union all 
 select 'Avg Price' Measure_Name ,avg(price) as Measure_Value from gold.fact_sales 
 union all 
 select 'Order Count' Measure_Name,count(distinct(order_number)) as  Measure_Value from gold.fact_sales
 union all 
 select 'Total Product' Measure_Name,count(distinct(product_key)) Measure_Value  from gold.dim_products
 union all 
 select 'Total Customer placed order ' Measure_Name,count(distinct(customer_key)) as  Measure_Value from gold.fact_sales

--- Magnitude--
-- Find total customer by Countries 
Select country,COUNT(customer_key) Total_Customers 
from gold.dim_customers group by country order by Total_Customers desc

-- Find total customers by gender
Select gender,COUNT(customer_key) Total_Customers 
from gold.dim_customers group by gender order by Total_Customers desc

-- Find total products by category
Select category,count(product_id) Total_Product 
from gold.dim_products group by category order by Total_Product desc

--What is the average costs in each category
select category,avg(cost) Avg_Cost 
from gold.dim_products group by category order by Avg_Cost desc

--what is the total revenue generated for each category?
select sum(f.sales_amount) Total_Revenue ,p.category 
from gold.fact_sales f left join gold.dim_products p on f.product_key=p.product_key 
group by p.category order by Total_Revenue desc

--Find total revenue is generated by each customer
select c.customer_key,c.first_name,c.last_name,sum(f.sales_amount) Total_amount 
from gold.fact_sales f left join gold.dim_customers c on f.customer_key=c.customer_key 
group by c.customer_key,c.first_name,c.last_name order by Total_amount desc

-- What is the distribution of sold items across countries?
select c.country,sum(f.quantity) Total_Quantity 
from gold.fact_sales f left join gold.dim_customers c on f.customer_key=c.customer_key 
group by c.country order by Total_Quantity desc

-- Ranking--
-- Which 5 Product generate the highest revenue ?
select top 5 sum(f.sales_amount) Total_Revenue ,p.product_name 
from gold.fact_sales f left join gold.dim_products p on f.product_key=p.product_key 
group by p.product_name 
order by Total_Revenue desc 

--What are the 5 worst - performing  products in terms of sales?
select top 5  sum(f.sales_amount) Total_Revenue ,p.product_name 
from gold.fact_sales f left join gold.dim_products p on f.product_key=p.product_key 
group by p.product_name 
order by Total_Revenue 
--using frame 
select * from (
select sum(f.sales_amount) Total_Revenue ,p.product_name, Row_number() over(order by sum(f.sales_amount) desc) as rank_product
from gold.fact_sales f left join gold.dim_products p on f.product_key=p.product_key 
group by p.product_name) t
 where t.rank_product<=5

 select * from (
select sum(f.sales_amount) Total_Revenue ,p.product_name, Row_number() over(order by sum(f.sales_amount) ) as rank_product
from gold.fact_sales f left join gold.dim_products p on f.product_key=p.product_key 
group by p.product_name) t
 where t.rank_product<=5


 select * from (
select sum(f.sales_amount) Total_Revenue ,p.product_name, Rank() over(order by sum(f.sales_amount) ) as rank_product
from gold.fact_sales f left join gold.dim_products p on f.product_key=p.product_key 
group by p.product_name) t
 where t.rank_product<=5

 --- Find the top 10 - customers who have generated the highest revenue
 select top 10 c.customer_key,c.first_name,c.last_name,sum(f.sales_amount) Total_amount 
 from gold.fact_sales f left join gold.dim_customers c on f.customer_key=c.customer_key 
 group by c.customer_key,c.first_name,c.last_name
 order by Total_amount desc
--3 customer with the fewest orders the placed
  select top 3 c.customer_key,c.first_name,c.last_name,count(distinct(order_number)) Total_order 
 from gold.fact_sales f left join gold.dim_customers c on f.customer_key=c.customer_key 
 group by c.customer_key,c.first_name,c.last_name
 order by Total_order 